<a href="https://colab.research.google.com/github/kokpingli/math_for_ml/blob/main/recitation1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recitation 1: An Introduction to Numpy

# Why Numpy?

If you are doing any computation in python, it is likely that you will want to use numpy. Not only does numpy provide a lot of functionality, but it is usually much faster than doing things in regular python because it calls fortran and C code.

In this colab, we will walk through some basics of numpy. Another great resource that goes into more detail about some of these topics and also has more general python topics is this tutorial from Stanford:
https://cs231n.github.io/python-numpy-tutorial/

In [1]:
# Import numpy. It is stanard to abbreviate this to np, so you don't have to type out numpy over and over.
import numpy as np

# The Numpy Array.


In some sense, the heart and soul behind numpy is the *ndarray* data type. We will first learn how to create an ndarray and what this data type can look like. Later, we will look at interesting things that we can do to ndarrays.

## Types of Arrays

### The 1d Array

One specific type of an ndarray is a 1d array. This is very similar to a list in python. We even instantiate a 1D array almost exactly like a list; the only difference is that we wrap np.array() around the list.

In [2]:
# To make the equivalent array in numpy we simply wrap it with np.array().
oned_array = np.array([1., 2., 3.])
print(oned_array)

[1. 2. 3.]


### The 2d Array (AKA Matrices and Vectors)



2d arrays correspond with matrices in math because they are kind of like lists but with rows and columns. We can instantiate a 2d array by calling np.array on a list of lists. Be careful that each inner list has the same size or else the array will not get constructed properly!

In [3]:
# An example of a 3x3 matrix.
mat = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
print('A 3x3 matrix:')
print(mat)

A 3x3 matrix:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]



One thing to be careful of is that vectors, as we usually think of them in math, are actually 2d arrays (either nx1 or 1xn). Vectors written as 1D arrays instead of 2d arrays can often cause bugs!

In [4]:
# Note that 1D arrays are not vectors as we would think of them in math.
# They are 2D arrays with 1 column i.e.
vect = np.array([[1.], [2.], [3.]])
print('A 3x1 matrix (aka vectory of length 3):')
print(vect)

A 3x1 matrix (aka vectory of length 3):
[[1.]
 [2.]
 [3.]]


### The ndarray

The ndarray corresponds with tensors in math. Don't worry if you haven't seen tensors before, but they are an n-dimensional extension of matrices. The highest dimensional ndarray we can visualize is the 3d-array. It can be thought of many matrices of the same size stack on top of each other. In other words, if a matrix is a square/rectangle then a 3d array is a cube/rectangular prism. Below is an image ([source](https://towardsdatascience.com/mastering-tensorflow-tensors-in-5-easy-steps-35f21998bb86)) showing a rank-1 tensor (1d array), rank-2 tensor (2d array), and rank-3 tensor (3d array).

![image.png](https://miro.medium.com/max/1260/1*W6s_CPw3y2K9S2cgYpLaBQ.png)

To make a 3d array we call np.array on a list of nested lists.

In [5]:
tensor = np.array([[[1., 2.,], [3., 4.]],
                   [[5., 6.], [7., 8.]],
                   [[9., 10.], [11., 12.]]])
print('A 3x2x2 tensor:')
print(tensor)

A 3x2x2 tensor:
[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]


### ndarray Shape

An important property of the ndarray is the shape. The shape is is a tuple of length $n$ for an ndarray which describes the dimensions of the array. For example, a matrix with three rows and two columns would have shape (3, 2).

One might expect using len on an ndarray would return the number of elements in the array. However, this is not always the case. It instead returns the leftmost number in the shape. For 2darrays this is the number of rows.

Below is code to show the shape and len of each ndarray we looked at above.

In [6]:
print(f'The 1D array we defined has shape {oned_array.shape} and length {len(oned_array)}.')
print(f'The matrix we defined has shape {mat.shape} and length {len(mat)}.')
print(f'The vector we defined has shape {vect.shape} and length {len(vect)}.')
print(f'The tensor we defined has shape {tensor.shape} and length {len(tensor)}.')

The 1D array we defined has shape (3,) and length 3.
The matrix we defined has shape (3, 3) and length 3.
The vector we defined has shape (3, 1) and length 3.
The tensor we defined has shape (3, 2, 2) and length 3.


### Other ways of creating ndarrays.

Creating ndarrays by calling np.array on nested lists can become tedius. Here are some other ways of quickly creating some standard ndarrays.

In [7]:
# arange is much like standard python "range" but makes a 1D array of integers.
print(' np.arange(5) =', np.arange(5))

# linspace creates a 1D array of floats by separating some range of numbers evenly.
#   * The first argument is the start of the range.
#   * The second argument is the end of the range to consider.
#   * The third argument is the number of elements to fill the array with.
print('\n np.linspace(1, 2, 8) =', np.linspace(1, 2, 5))

# zeros creates a ndarray with all 0 elements. It takes the shape of the ndarray
# that we want to produce.
print('\n Example of 1D array with all zeros: np.zeros((3,)) = ', np.zeros((3,)))
print('\n Example of 2D array with all zeros: np.zeros((3, 2)) = ...')
print(np.zeros((3, 2)))

# ones creates a ndarray with all 1 elements. It takes the shape of the ndarray
# that we want to produce.
print('\n Example of 1D array with all zeros: np.ones((3,)) = ', np.ones((3,)))
print('\n Example of 2D array with all zeros: np.ones((3, 2)) = ...')
print(np.ones((3, 2)))


 np.arange(5) = [0 1 2 3 4]

 np.linspace(1, 2, 8) = [1.   1.25 1.5  1.75 2.  ]

 Example of 1D array with all zeros: np.zeros((3,)) =  [0. 0. 0.]

 Example of 2D array with all zeros: np.zeros((3, 2)) = ...
[[0. 0.]
 [0. 0.]
 [0. 0.]]

 Example of 1D array with all zeros: np.ones((3,)) =  [1. 1. 1.]

 Example of 2D array with all zeros: np.ones((3, 2)) = ...
[[1. 1.]
 [1. 1.]
 [1. 1.]]


## Reshaping Arrays


### The Reshape Function

One cool thing about ndarrays is that once you initialize one you can change the shape with the "reshape" method! You can even do things like change a 1d array into a 3d array.

Reasoning about how exactly an array will be reshaped is a bit tricky. Below is an example of a 1d array being transformed into a 2d array (taken from here [link text](https://towardsdatascience.com/reshaping-numpy-arrays-in-python-a-step-by-step-pictorial-tutorial-aed5f471cf0b). This blog post has some great resources on reshaping arrays).

![image.png](https://miro.medium.com/max/977/1*16lfH-A_kiDmyxe1Sm2dQA.png)

a1.reshape((3, 4))

![image.png](https://miro.medium.com/max/362/1*b0Eh1M1w4d9gKIhN8Fdjcg.png)


Here are some more examples in code of using reshape:

In [8]:
arr = np.arange(8) # Create a 1d array o shape (8,)
print(f'Array as a 1d array with shape {arr.shape}:')
print(arr)
# Reshape to a 2d array. A couple things to keep in mind:
#   * The number of elements in the array must be compatible with the new shape.
#   * Calling reshape will return a new array. We must assign arr to the output.
arr = arr.reshape((4, 2))
print(f'After reshaping to 2d array with shape {arr.shape}:')
print(arr)
# Reshape to a 3d array.
arr = arr.reshape((2, 2, 2))
print(f'After reshaping to 3d array with shape {arr.shape}:')
print(arr)

Array as a 1d array with shape (8,):
[0 1 2 3 4 5 6 7]
After reshaping to 2d array with shape (4, 2):
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
After reshaping to 3d array with shape (2, 2, 2):
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


One neat trick is that we can put a -1 in one spot and numpy will infer what value must be in that spot e.g...


In [9]:
# The first spot must be a 2 since 8 / 4 = 2
arr = arr.reshape((2, -1))
print(f'First shape = {arr.shape}')
# The second spot must be a 2 since 8 / 2 / 2 = 2
arr = arr.reshape((2, -1, 2))
print(f'Second shape = {arr.shape}')
# This is especially useful for making vectors where you don't necessarily know
# how many elements are in the array e.g.
arr = arr.reshape((-1, 1))
print(f'Thrid shape = {arr.shape}')

First shape = (2, 4)
Second shape = (2, 2, 2)
Thrid shape = (8, 1)


### The Flatten Function

The function "flatten" will reshape the array back into a 1d array.

In [10]:
# Note that flatten also returns a new array that we need to assign to arr like reshape.
arr = arr.flatten()
print('The flatenned array: ')
print(arr)

The flatenned array: 
[0 1 2 3 4 5 6 7]


### Transposing

Lastly, we can put a .T after a matrix in order to take the transpose. Note, that reshaping a mxn matrix into an nxm matrix will not produce the same thing as taking the transpose!

In [11]:
mat = np.arange(1, 13).reshape(4, 3)
print('The original matrix:')
print(mat)
print('The transpose of the matrix:')
print(mat.T)
print('Reshaping the matrix to (3, 4)')
print(mat.reshape(3, 4))

The original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
The transpose of the matrix:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Reshaping the matrix to (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Exercises

Give three different ways we can make a 3x3 matrix of all 1s.

In [24]:
# Method 1:
mat = np.array([[1., 1., 1.], [1., 1., 1.], [1., 1., 1]])
print(mat)

# Method 2:
mat = np.ones((3,3))
print(mat)

# Method 3:
mat = np.array([np.linspace(1,1,3), np.linspace(1,1,3), np.linspace(1,1,3)])
print(mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


For each of the following arrays below, which transformation will make "start" match "end"

In [33]:
"""Question 1"""
start = np.array([2, 10, 2, 6]).reshape(2,2)
end = np.array([[2, 10], [2, 6]])
# YOUR WORK TO TRANSFORM START HERE

assert start.shape == end.shape and np.allclose(start, end, atol=1e-6), 'Question 1 Incorrect.'

"""Question 2"""
start = np.array([[5, 2], [1, 3]]).T
end = np.array([[5, 1], [2, 3]])
# YOUR WORK TO TRANSFORM START HERE

assert start.shape == end.shape and np.allclose(start, end, atol=1e-6), 'Question 2 Incorrect.'

"""Question 3"""
start = np.array([[1, 2, 3]]).flatten()
end = np.array([1, 2, 3])
# YOUR WORK TO TRANSFORM START HERE

assert start.shape == end.shape and np.abs(np.sum(start - end)) < 1e-6, 'Question 3 Incorrect.'

print('SUCCESS!')

SUCCESS!


Instantiate a 2x2 array so that when flatten is called on it, it returns the 1d array [5, 2, 3 6]

In [35]:
answer = np.array([[5, 2], [3, 6]])

print(answer)
print(answer.flatten())

[[5 2]
 [3 6]]
[5 2 3 6]


Using a series of operations take the matrix
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6 \\
7 & 8 & 9 & 10 & 11 & 12
\end{bmatrix}
and ends up at the matrix.
\begin{bmatrix}
1 & 4 & 7 & 10 \\
2 & 5 & 8 & 11 \\
3 & 6 & 9 & 12 \\
\end{bmatrix}

In [40]:
start = np.arange(1, 13).reshape((2, 6))

end = start.reshape((4,3)).T

print(end)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


Write a function that checks if a given array can be reshaped into a 3d array with shape (3, 5, 2) without using the reshape function and returns True or False.

In [ ]:
def can_reshape(arr):
  # YOUR WORK HERE
  pass

if not can_reshape(np.arange(30)):
  print('Incorrect.')
elif not can_reshape(np.ones((5, 3, 2))):
  print('Incorrect.')
elif can_reshape(np.ones((3, 2, 6))):
  print('Incorrect.')
elif can_reshape(np.zeros((4, 5))):
  print('Incorrect.')
else:
  print('Correct!')

## Indexing Arrays

There are many complex ways of indexing ndarrays but we will go over the basics here.

### Getting a Single Element

We will now walk through how to access particular elements of arrays. The easiest version of this is getting a single number from an ndarray. Like with python lists, we use a square bracket after the array to indicate the index of the element we would like. However, if we are using an ndarray, we must provide $n$ elements. Here are some examples of this:

In [ ]:
oned = np.arange(4)
print('1d array:')
print(oned)
print('The element at index 3 is ', oned[3])

twod = np.arange(9).reshape(3, 3)
print('\n2d array:')
print(twod)
print('The element at index (1,2) is ', twod[1, 2])

threed = np.arange(8).reshape(2, 2, 2)
print('\n3d array:')
print(threed)
print('The element at index (0,1,0) is ', threed[0, 1, 0])

### Getting Multiple Elements

ndarrays also allow for providing lists of indices. We can provide a list of the same length for every dimension, and numpy will construct a 1d array of the selected elements. Here's how it works below:

In [ ]:
oned = np.arange(4)
print('1d array:')
print(oned)
print('The elements at index 1 and 3 are ', oned[[1, 3]])

twod = np.arange(9).reshape(3, 3)
print('\n2d array:')
print(twod)
print('The elements at index (1,2), (2, 2) and (0, 0) are ', twod[[1, 2, 0], [2, 2, 0]])

threed = np.arange(8).reshape(2, 2, 2)
print('\n3d array:')
print(threed)
print('The elements at index (0,1,0) and (1, 1, 1) are ', threed[[0, 1], [1, 1], [0, 1]])

### Slicing

Like python lists, we can slice but in multiple dimensions. Instead of providing a single index of a dimension in the ndarray, we can provide an $a$:$b$ range, where $a$ and $b$ are indices. If $a$ is not provided (i.e. :$b$) then it is treated as the start up to $b$. If $b$ is not provided (i.e. $a$:) then it is treated as index $a$ to the end. If we just put :, then we select all of the elements for that dimension.

When a single index is provided for a dimension that dimension is removed, but if a slice is provided that dimension is kept. To illuminate this point, we can enumerate over the different possibilities in a 2d array.

In [ ]:
A = np.arange(9).reshape(3, 3)
print('The matrix A is: ')
print(A)

# Slicing for both dimensions. Chop off the first column and the last row.
print('\n Selecting A[:2, 1:]...')
print('The shape is ', A[:2, 1:].shape)
print(A[:2, 1:])

# Slicing for one dimension. Pick out the column at index 1.
print('\n Selecting A[:, 1]...')
print('The shape is ', A[:, 1].shape)
print(A[:, 1])

# Select a single element:
print('\n Selecting A[2, 1]...')
print('The return is no longer an ndarray! It is a ', type(A[2, 1]))
print(A[2, 1])

We can also combine slicing with lists of indices to pick out multiple rows or columns.

In [ ]:
A = np.arange(9).reshape(3, 3)
print('The matrix A is: ')
print(A)

# Get the first and last rows.
print('\n The first and last rows are')
print(A[[0, 2], :])

# Get the first and last columns.
print('\n The first and last columns are')
print(A[:, [0, 2]])

### Exercises

Select all of the even numbers in the following arrays.

In [ ]:
"""Question 1"""
arr1 = np.arange(1, 8)
evens = ... # YOUR WORK HERE
print(evens)

"""Question 2"""
arr2 = np.array([[2, 55, 3],
                 [93, 11, 4],
                 [1, 1, 1],
                 [3, 6, 8]])
evens = ... # YOUR WORK HERE
print(evens)

Select all rows in the matrix that have at least 1.

In [ ]:
mat = np.array([[0, 0, 0, 0, 0],
                [0, 1, 0, 0, 0],
                [0, 0, 0, 0, 1],
                [0, 0, 0, 0, 0]])
rows = ... # YOUR WORK HERE
print(rows)

Select all columns in the matrix that have at least one 1.

In [ ]:
mat = np.array([[0, 0, 0, 0, 0],
                [0, 1, 0, 0, 0],
                [0, 0, 0, 0, 1],
                [0, 0, 0, 0, 0]])
rows = ... # YOUR WORK HERE
print(rows)

For the following, give the shape of the array of indexing.

In [ ]:
"""Question 1"""
q1 = np.arange(16).reshape(4, 4)
q1 = q1[:, [3, 2]]
shape = ... # YOUR ANSWER HERE IN TUPLE FORM
assert q1.shape == shape, 'Question 1 Incorrect.'

"""Question 2"""
q2 = np.arange(16).reshape(4, 4)
q2 = q2[[1, 2], [3, 2]]
shape = ... # YOUR ANSWER HERE IN TUPLE FORM
assert q2.shape == shape, 'Question 2 Incorrect.'

"""Question 3"""
q3 = np.arange(27).reshape(3, 3, 3)
q3 = q3[:2, :, 0]
shape = ... # YOUR ANSWER HERE IN TUPLE FORM
assert q3.shape == shape, 'Question 3 Incorrect.'

"""Question 3"""
q4 = np.arange(16).reshape(4, 4)
q4 = q4[:, [1]]
shape = ... # YOUR ANSWER HERE IN TUPLE FORM
assert q4.shape == shape, 'Question 4 Incorrect.'

print('Success!')

# Numpy Operations

## Basic Math

A lot of basic math operations involving an ndarray and a number will work as one would expect. This works with 1d arrays, 2d arrays, 3d arrays, etc, but I will show some examples with 2d arrays below:

In [ ]:
A = np.arange(4).reshape(2, 2)
print('The matrix A is: ')
print(A)

# If we want to add 2 to all elements of the matrix:
print('\n A + 2 = ')
print(A + 2)

# If we want to multiply all elements by 3:
print('\n A * 3 = ')
print(A * 3)

# If we want to divide all elements by 2:
print('\n A / 2 = ')
print(A / 2)

# If we want to square all elements:
print('\n A ** 2 = ')
print(A ** 2)

## ndarray Math

### Element-Wise Operations

If two ndarrays have the same shape, we can do standard mathematical operations between them and the result will be an ndarray where the operation has been applied for each element, i.e. (A * B)\[i, j] =  A\[i, j] * B\[i, j]

In [ ]:
A = np.arange(4).reshape(2, 2)
print('The matrix A is: ')
print(A)

B = np.array([[1, 1], [2, 2]])
print('The matrix B is: ')
print(B)

print('\n A + B = ')
print(A + B)

print('\n A * B =')
print(A * B)

print('\n A / B = ')
print(A / B)

print('\n A ** B = ')
print(A ** B)

### Broadcasting

Broadcasting in numpy basically allows one to do operations between arrays of differing shapes. The rules behind broadcasting are somewhat complex (a good description can be found [here](https://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)). Here, we will just go over one useful instance of broadcasting:

In [ ]:
A = np.arange(9).reshape(3, 3)
print('Matrix A = ')
print(A)
v1 = np.arange(1, 4).reshape(1, 3)
print('Vector v1 = ')
print(v1)
v2 = np.arange(1, 4).reshape(3, 1)
print('Vector v2 = ')
print(v2)

# To multiply the first column by 1, the second row by 2, and the third row by 3...
print('\n A * v1 = ')
print(A * v1)

# To multiply the first row by 1, the second row by 2, and the third row by 3...
print('\n A * v2 = ')
print(A * v2)

### Matrix Products


If we want to do products between matrices or vectors, we can use the \@ operator (or np.matmul).

In [ ]:
A = np.arange(9).reshape(3, 3)
print('Matrix A = ')
print(A)
B = np.arange(9).reshape(3, 3) * -3 + 2
print('Matrix B = ')
print(B)
v1 = np.arange(3).reshape(-1, 1)
print('Vector v1 =')
print(v1)
v2 = np.arange(3).reshape(-1, 1) * 2 - 1
print('Vector v2 =')
print(v2)

print('\n Perform an outer product between vectors v1 and v2.')
print(v1 @ v2.T)

print('\n Perform an inner product between v1 and v2.')
print(v1.T @ v2)

print('\n Compute A v1 (matrix-vector product)')
print(A @ v1)

print('\n Compute A B (matrix-matrix product)')
print(A @ B)

### Exercises



For each code block below, determine if the code is correct or not. If it is incorrect, fix it to produce the correct answer. You may need to work out the correct answer on paper to make sure you are doing it correctly.

$C = AB$

In [ ]:
# Fix the following code

A = np.array([[3,5],
              [7,11]])
B = np.array([[1,2],
              [3,4]])

C = A @ B
print(C)

[[18 26]
 [40 58]]


$y = u^Tv$

In [ ]:
u = np.array([3,5,7]).reshape((3, 1))
v = np.array([2,3,4]).reshape((3, 1))
y = u.T @ v
print(y)

[[49]]


$Y = uv^T$

In [ ]:
u = np.array([3,5,7]).reshape(3, 1)
v = np.array([2,3,4]).reshape(3, 1)
Y = u @ v.T
print(Y)

[[ 6  9 12]
 [10 15 20]
 [14 21 28]]


## Numpy Functions

Numpy provides several very useful functions such as np.sum, np.mean, np.std (computes the standard deviation), and np.max. By default, these quantities are computed over all elements, but we can use the "axis" keyword to compute only along certain dimensions.

For example, if we have a 2d array, setting axis=0 will compute the quantities with respect to rows, and setting axis=1 will compute the quantities with respect to columns. Below are some examples of this:

In [ ]:
A = np.arange(4).reshape(2, 2)
print('The matrix A is: ')
print(A)

print('\n Sum over all elements of A: ')
print(np.sum(A))

print('\n Take mean over the rows of A: ')
print(np.mean(A, axis=0))

print('\n Find max over columns of A: ')
print(np.max(A, axis=1))

print(np.mean(np.max(A, axis=1)))

The matrix A is: 
[[0 1]
 [2 3]]

 Sum over all elements of A: 
6

 Take mean over the rows of A: 
[1. 2.]

 Find max over columns of A: 
[1 3]
2.0


### Exercises

Suppose we have been recruited by the Tazza cafe (GHC 3rd Floor) to help them compute some statistics. They have measured how many cups of coffee were sold on each day of the week for 4 weeks and organized it into a matrix, $D$. The $(i, j)$ entry of $D$ is how many cups of coffee were sold on the $j^{th}$ day of the $i^{th}$ week.

In [ ]:
D = np.array([[ 2, 10, 18, 13,  4,  3, 19],
              [10,  6, 13, 10,  1,  2, 17],
              [ 6, 13, 13,  2,  9, 20, 19],
              [18, 14, 18,  2,  4, 19, 24]])

How many cups of coffee were sold in total during this time period?

In [ ]:
ans = ... # YOUR WORK HERE.

assert ans == 309, 'Incorrect.'
print('Correct!')

Give a 1d vector that shows the average cups of coffee sold for each day.

In [ ]:
ans = ... # YOUR WORK HERE

assert list(ans) == [9., 10.75, 15.5, 6.75, 4.5, 11., 19.75], 'Incorrect.'
print('Correct!')

What was the most coffee sold in one week?

In [ ]:
ans = ... # YOUR WORK HERE

assert ans == 99, 'Incorrect.'
print('Correct!')

## Some Useful Linear Algebra Functions

Below I have listed some other numpy functions relating to linear algebra that might prove useful.

In [ ]:
A = np.arange(4).reshape(2, 2)
print('The matrix A is: ')
print(A)
y = np.arange(2).reshape(-1, 1)
print('The vector y is: ')
print(y)

print('\n We can solve the linear system Ax=y. x = ...')
print(np.linalg.solve(A, y))

print('\n We can compute the inverse of A. A^-1 = ')
print(np.linalg.inv(A))

print('\n We can compute the determinant of A. det(A) =')
print(np.linalg.det(A))

### Exercise

Tazza cafe wants more help from us. For the last three months they have recorded how much coffee, paninis, and oat milk matcha lattes they have sold and the total profits. However, they have somehow lost the menu and forgot how much they charge for each. They have the following information:

<table>
<tr>
<th>Month</th>
<th>Coffee Sold</th>
<th>Paninis Sold</th>
<th>Oat Milk Match Lattes Sold</th>
<th>Money Made</th>
</tr>
<tr>
<td>1</td>
<td>15</td>
<td>3</td>
<td>1</td>
<td>100</td>
</tr>
<tr>
<td>2</td>
<td>25</td>
<td>3</td>
<td>0</td>
<td>150</td>
</tr>
<tr>
<td>3</td>
<td>10</td>
<td>5</td>
<td>2</td>
<td>200</td>
</tr>
</table>

Using numpy, how much does each item cost?

In [ ]:
costs = ... # YOUR WORK HERE

assert np.sum(np.abs(costs.flatten() - np.array([5., 12., 8.]))) < 1e-6, 'Incorrect.'
print('Success!')

Tazza cafe has made several projections for how much of each item they think they will sell in the next coming months (stored as the matrix "projections" below). Help Tazza calculate how much money they can expect to make for each of these months.

In [ ]:
projections = np.array([[20, 5, 16],
                        [25, 4, 19],
                        [4, 3, 10],
                        [1, 1, 1000]])
answer = ... # YOUR WORK HERE.

assert np.sum(np.abs(answer.flatten() - np.array([288., 325., 136., 8017.]))) < 1e-6, 'Incorrect.'
print('Success!')